<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions
        targetNamespace="urn:oasis:names:tc:xacml:2.0:context:schema:os"
        xmlns:tns="urn:oasis:names:tc:xacml:2.0:context:schema:os"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
		xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
		xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns:xacml-context="urn:oasis:names:tc:xacml:2.0:context:schema:os"
        xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">

  <wsdl:types>
    <xs:schema>
      <xs:import namespace="urn:oasis:names:tc:xacml:2.0:policy:schema:os" 
      schemaLocation="http://docs.oasis-open.org/xacml/access_control-xacml-2.0-policy-schema-os.xsd"/>
      <xs:import namespace="urn:oasis:names:tc:xacml:2.0:context:schema:os" 
      schemaLocation="http://docs.oasis-open.org/xacml/access_control-xacml-2.0-context-schema-os.xsd"/>
    </xs:schema>
  </wsdl:types>
  
  <wsdl:message name="XACML20Request">
    <wsdl:part name="request" element="xacml-context:Request" />
  </wsdl:message>
  <wsdl:message name="XACML20Response">
    <wsdl:part name="response" element="xacml-context:Response" />
  </wsdl:message>
  
  <wsdl:portType name="Xacml20PdpPort">
    <wsdl:operation name="decide">
      <wsdl:input message="tns:XACML20Request"/>
      <wsdl:output message="tns:XACML20Response"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="Xacml20SoapBinding" type="tns:Xacml20PdpPort">
      <soap:binding style="document"  transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="decide">
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
    
   <wsdl:binding name="Xacml20PoxBinding" type="tns:Xacml20PdpPort">	
   	  <http:binding verb="POST"/>
   	  <wsdl:operation name="decide">
            <http:operation location="/pox"/>
            <wsdl:input>
                <mime:mimeXml part="request"/>
            </wsdl:input>
            <wsdl:output>
                <mime:mimeXml part="response"/>
            </wsdl:output>
        </wsdl:operation>
   </wsdl:binding>
   
   <wsdl:service name="Xacml20SoapService"> 
      <wsdl:port name="Xacml20PdpPort" binding="tns:Xacml20SoapBinding">
         <soap:address location="http://localhost:8080/xacml-ws/soap"/>
      </wsdl:port>
   </wsdl:service>
   
   <wsdl:service name="Xacml20PoxService"> 
      <wsdl:port name="Xacml20PdpPort" binding="tns:Xacml20PoxBinding">
         <http:address location="http://localhost:8080/xacml-ws/pox"/>
   	</wsdl:port>
   </wsdl:service>
   

</wsdl:definitions>